import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LogoutBtn from "./LogoutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import ReduxProvider from "../redux/provider";
import HeaderLoginP from "./HeaderLoginP";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "M-market",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  // console.log(session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/" className="logo">
            Home
          </Link>
          <ReduxProvider>
            <Link href="/list">List</Link>
            <Link href="/cart">Cart</Link>
          </ReduxProvider>
          <Link href="/board">Q&A</Link>
          {session ? (
            <div className="head-design1">
              <div className="head-memberInfo">{session.user.name}</div>
              <LogoutBtn />
            </div>
          ) : (
            <div className="head-design1">
              <ReduxProvider>
                <HeaderLoginP />
              </ReduxProvider>
            </div>
          )}
        </div>

        <ReduxProvider>{children}</ReduxProvider>

        <div className="footer">Copyright 2024 by Moon</div>
      </body>
    </html>
  );
}
