import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import LogoutBtn from "./LogoutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import SignupBtn from "./SignupBtn";
import ReduxProvider from "./login/redux/provider";
import HeadBtn from "./login/redux/HeadBtn";
//import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  // console.log(session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/" className="logo">
            Home
          </Link>
          <Link href="/list">List</Link>
          <Link href="/cart">Cart</Link>
          <Link href="/board">Q&A</Link>

          {session ? (
            <span className="head-design1">
              <div className="head-memberInfo">{session.user.name}</div>
              <LogoutBtn />
            </span>
          ) : (
            <div className="head-design1">
              <LoginBtn />
              <SignupBtn />
            </div>
          )}
        </div>
        <ReduxProvider>
          {children}

          {/* <Header /> */}
          <HeadBtn />
        </ReduxProvider>

        <div className="footer">Copyright 2024 by Moon</div>
      </body>
    </html>
  );
}
